### ISSUE TITLE
Failed test ''MyApp->view' isa 'Catalyst::View::Template''

### ISSUE THREAD

**Issue by szabgab** [ap/Catalyst-View-Template#1]
After cloning this repo and running `cpanm --installdeps .`

I get the following error:

```
 make test
PERL_DL_NONLAZY=1 "/opt/perl-5.30.1/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/basic.t .. require MyApp::View::Appconfig was successful but the package is not defined. at /home/gabor/perl5/lib/perl5/Catalyst/Utils.pm line 315.
require MyApp::View::Pkgconfig was successful but the package is not defined. at /home/gabor/perl5/lib/perl5/Catalyst/Utils.pm line 315.
[warn] Attempted to use view 'MyApp::View::PkgConfig', but does not exist
t/basic.t .. 1/43 
#   Failed test ''MyApp->view' isa 'Catalyst::View::Template''
#   at t/basic.t line 13.
#     'MyApp->view' isn't a 'Catalyst::View::Template'
Can't locate object method "render" via package "MyApp::View::Pkgconfig" (perhaps you forgot to load "MyApp::View::Pkgconfig"?) at t/basic.t line 14.
# Looks like your test exited with 255 just after 1.
t/basic.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 43/43 subtests 

Test Summary Report
-------------------
t/basic.t (Wstat: 65280 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 43 tests but ran 1.
Files=1, Tests=1,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.43 cusr  0.03 csys =  0.48 CPU)
Result: FAIL
Failed 1/1 test programs. 1/1 subtests failed.
make: *** [Makefile:869: test_dynamic] Error 255
```

**Comment by ap** [comment]
Oh… my… goodness.

The TestApp view class modules have the correctly camel-cased name in my source tree:

````
$ ll t/lib/MyApp/View
total 40
-rw-r--r--  1 ap  staff  226 24 Oct 20:14 AltContentType.pm
-rw-r--r--  1 ap  staff  145 24 Oct 20:14 AppConfig.pm
-rw-r--r--  1 ap  staff  852 24 Oct 20:14 DynamicPath.pm
-rw-r--r--  1 ap  staff  234 24 Oct 20:14 PkgConfig.pm
-rw-r--r--  1 ap  staff  241 24 Oct 20:16 TemplateClass.pm
````

But that’s not what Git sees:
````
$ git ls t/lib/MyApp/View
t/lib/MyApp/View/AltContentType.pm
t/lib/MyApp/View/Appconfig.pm
t/lib/MyApp/View/DynamicPath.pm
t/lib/MyApp/View/Pkgconfig.pm
t/lib/MyApp/View/TemplateClass.pm
````

Note the difference in casing! `PkgConfig.pm` vs `Pkgconfig.pm`.

Here’s what happened:

1. My machine is a Mac. Its filesystem is case-preserving but case-insensitive.

2. I used the test suite from Catalyst::View::TT as a starting point. In there are files called `Pkgconfig.pm` and `Appconfig.pm`. Of course I committed these.

3. I refactored the test suite a bunch. And then some. And some more. One of my changes was to capitalise the C in “Config” in the names of these classes – changing all the mentions in code as well as renaming the files.

4. *Because the filesystem is case-insensitive*, Git could still find the same files under their old names, so it didn’t notice I had renamed the files. And I in turn didn’t notice that Git didn’t notice that anything had changed. So the rename was never recorded by Git.

5. My release process is just `perl Makefile.PL && make dist`. Part of my `Makefile.PL` is to generate `MANIFEST`… *from Git*. EUMM then reads `MANIFEST` to collect the files to put in the dist dir. And *because the filesystem is case-insensitive*, just as Git succeeds when it goes looking for those files using their old names, so succeeds EUMM. So it creates a tarball that contains the files under their *non*-camel-cased names. And even though I carefully inspect tarballs on release, this was a flaw too subtle for me to pick up on by eye.

6. This broken tarball works on my machine! It installed on another perl just fine. That’s because the names in the Perl code *all* use the camel-cased names: both the references to the classes and their package statements use the same casing. And *because the filesystem is case-insensitive*, when perl tries to find the files under their camel-cased names… even though the filenames are wrong… it succeeds! So to a perl on my system, everything checks out.

That’s the story of how I shipped a broken tarball to CPAN.

Thank you very much for reporting this. I’ve not yet gotten my (blood red) daily CPAN Testers report.

P.S.: The story apparently doesn’t actually end there, because Windows also has a case-preserving case-insensitive filesystem, and yet the Windows-based CPAN Testers reports are all FAILs just like the Linux- and BSD-based ones. More intriguingly, *I get the same failure myself* now if I start with a fresh tarball. In one of my perls. That’s not making sense to me right now – the story I had above seemed airtight. So I checked and I’m not hallucinating that it installed fine in the other perl – that really happened. I don’t yet know what’s going on.

**Comment by ap** [comment]
(Also, 👋 long time no talk.)

**Comment by ap** [comment]
Fixed in 51aa08bbc1c2bbe5c05b8670332093c19ed1bb22, which is winding its way to CPAN as we speak.

**Comment by szabgab** [comment]
Lack of sleep? :smile: lack of :coffee: ?

**Comment by ap** [comment]
🙂 Lack of sleep always applies. 🙁 But I don’t know how I would have caught this, frankly. I wasn’t even on the lookout for the issue. (The simple answer is obviously that I need to be working out of a case-sensitive filesystem…)

**Comment by szabgab** [comment]
I've sent you a pull request to set up a ci system. That will catch theses
things and probably others as well.
